load("@rules_cc//cc:defs.bzl", "cc_binary", "cc_library")

cc_library(
	name = "UI",
	hdrs = [
		"UI.h",
	],
	srcs = [
		"UI.cpp",
	],
	deps = [
		"@rules_qt//:qt_core",
		"@rules_qt//:qt_widgets",
		"@rules_qt//:qt_gui",
	],
)
