load("@rules_cc//cc:defs.bzl", "cc_binary", "cc_library")

cc_library(
	name = "UI",
	includes = [
		"/usr/include/x86_64-linux-gnu/qt6",
	],
	hdrs = [
		"UI.h",
	],
	srcs = [
		"UI.cpp",
	],
	visibility = [
		"//visibility:public"
	],
)
